import type { Lesson } from "./content-types";
import type { LSpec } from "./gen";
import { mkLs } from "./gen";

/* ================= React — ۱۲ درس ================= */
const REACT: LSpec[] = [
  {
    id: "react-b1", t: "JSX و قوانین آن",
    p: "JSX سینتکسی است که شبیه HTML در جاوااسکریپت نوشته می‌شود و به createElement کامپایل می‌شود؛ چند تفاوت مهم با HTML دارد که باید بدانی.",
    pts: ["class برابر className و for برابر htmlFor است", "هر JSX باید یک ریشه داشته باشد یا از Fragment <> </> استفاده کنی", "عبارت‌ها داخل {} قرار می‌گیرند و style شیء است"],
    code: ["tsx", "jsx.tsx", "function Card({ title }: { title: string }) {\n  return (\n    <>\n      <h2 className=\"card\">{title}</h2>\n      <p style={{ color: 'teal' }}>{2 + 2}</p>\n    </>\n  );\n}"],
    q: [["چرا در JSX از className استفاده می‌شود؟", ["قشنگ‌تر است", "چون class در جاوااسکریپت کلمه رزرو است", "اجباری نیست", "برای CSS است"], 1, "JSX در واقع جاوااسکریپت است و class رزرو شده؛ پس React از className استفاده می‌کند."]],
  },
  {
    id: "react-b2", t: "Props و جریان داده یک‌طرفه",
    p: "Props ورودی‌های فقط‌خواندنی یک کامپوننت‌اند و داده در React همیشه از پدر به فرزند جاری است؛ فرزند برای تغییر، تابعی را از پدر صدا می‌زند.",
    pts: ["props را هرگز تغییر نده — فقط‌خواندنی‌اند", "برای ارتباط فرزند→پدر، handler از پدر پاس بده", "children خاص‌ترین prop است که محتوای بین تگ‌هاست"],
    code: ["tsx", "props.tsx", "function Button({ label, onClick }: {\n  label: string; onClick: () => void;\n}) {\n  return <button onClick={onClick}>{label}</button>;\n}\n\nfunction App() {\n  return <Button label=\"بزن\" onClick={() => alert('!')} />;\n}"],
    q: [["چرا جریان داده در React یک‌طرفه است؟", ["تصادفی", "چون پیش‌بینی‌پذیری و دیباگ را ساده می‌کند و تغییرات متمرکز می‌شود", "برای سرعت", "محدودیت فنی"], 1, "وقتی داده فقط پایین می‌رود، همیشه می‌دانی هر مقدار از کجا آمده و کجا تغییر می‌کند."]],
  },
  {
    id: "react-b3", t: "State و رندر مجدد",
    p: "State داده‌ای است که با تغییرش، کامپوننت دوباره رندر می‌شود. setState همگام نیست و باید با callback یا مقدار جدید کار کنی.",
    pts: ["useState یک جفت [مقدار، setter] برمی‌گرداند", "برای مقدار وابسته به قبلی، از setter(prev => ...) استفاده کن", "رندر فقط یعنی ساخت VDOM؛ تغییر واقعی با reconciliation است"],
    code: ["tsx", "state.tsx", "function Counter() {\n  const [n, setN] = useState(0);\n  return (\n    <button onClick={() => setN(p => p + 1)}>\n      {n}\n    </button>\n  );\n}"],
    q: [["چرا setN(n+1) دوبار پشت‌سرهم، n را فقط یکی زیاد می‌کند؟", ["باگ است", "چون n در هر دو فراخوان همان مقدار قدیمی است؛ باید setN(p=>p+1) بزنی", "کند است", "ممکن نیست"], 1, "setState همگام نیست؛ اگر از متغیر فعلی استفاده کنی، هر دو از مقدار یکسان حساب می‌کنند. تابع updater راه‌حل است."]],
  },
  {
    id: "react-b4", t: "لیست‌ها و کلید",
    p: "برای رندر لیست از map استفاده می‌کنی و هر عنصر باید key یکتا داشته باشد تا React بفهمد کدام آیتم عوض شده و کمترین تغییر DOM را بزند.",
    pts: ["key باید بین خواهرها یکتا و پایدار باشد", "از ایندکس به‌عنوان key فقط وقتی لیست تغییر نمی‌کند استفاده کن", "map را داخل JSX با {} قرار بده"],
    code: ["tsx", "list.tsx", "function List({ items }: { items: { id: number; t: string }[] }) {\n  return (\n    <ul>\n      {items.map(it => (\n        <li key={it.id}>{it.t}</li>\n      ))}\n    </ul>\n  );\n}"],
    warn: "استفاده از ایندکس به‌عنوان key وقتی آیتم‌ها حذف/اضافه می‌شوند، باعث رندر اشتباه و از دست رفتن state عناصر می‌شود.",
    q: [["چرا key لازم است؟", ["برای CSS", "تا React هویت عناصر را بین رندرها تشخیص دهد و کمترین تغییر را بزند", "اجباری نیست", "برای مرتب‌سازی"], 1, "بدون key، React نمی‌داند کدام عنصر کدام است و ممکن است همه را از نو بسازد یا state را جابه‌جا کند."]],
  },
  {
    id: "react-b5", t: "useEffect و همگام‌سازی",
    p: "useEffect برای اثرهایی است که خارج از رندر رخ می‌دهند: دریافت داده، اشتراک، تایمر. آرایه وابستگی تعیین می‌کند چه زمانی اجرا شود.",
    pts: ["[] یعنی فقط یک‌بار هنگام mount", "[x] یعنی هر بار x عوض شد", "بازگرداندن تابع، پاک‌سازی است که قبل از اجرای بعدی یا unmount صدا می‌شود"],
    code: ["tsx", "effect.tsx", "useEffect(() => {\n  const id = setInterval(() => setN(n => n + 1), 1000);\n  return () => clearInterval(id);   // پاک‌سازی\n}, []);"],
    q: [["چرا پاک‌سازی در useEffect مهم است؟", ["کد کوتاه می‌شود", "تا اشتراک‌ها و تایمرها بعد از unmount نشت نکنند و حافظه هدر نرود", "اجباری نیست", "برای سرعت"], 1, "بدون پاک‌سازی، تایمرها و listenerها بعد از حذف کامپوننت هم زنده می‌مانند و memory leak می‌سازند."]],
  },
  {
    id: "react-b6", t: "فرم‌های کنترل‌شده",
    p: "در فرم کنترل‌شده، مقدار input از state می‌آید و با onChange آپدیت می‌شود؛ پس React تنها منبع حقیقت است و اعتبارسنجی ساده می‌شود.",
    pts: ["value={state} و onChange={e => set(e.target.value)}", "فرم uncontrolled با ref برای دسترسی مستقیم DOM است", "onSubmit را با preventDefault بگیر"],
    code: ["tsx", "form.tsx", "function Form() {\n  const [name, setName] = useState('');\n  return (\n    <form onSubmit={e => { e.preventDefault(); alert(name); }}>\n      <input value={name} onChange={e => setName(e.target.value)} />\n      <button>ثبت</button>\n    </form>\n  );\n}"],
    q: [["مزیت فرم کنترل‌شده چیست؟", ["سریع‌تر است", "React تنها منبع حقیقت است؛ اعتبارسنجی و مقدار همیشه در state است", "کد کمتر است", "CSS راحت‌تر است"], 1, "چون مقدار از state می‌آید، همیشه مقدار واقعی را داری و می‌توانی لحظه‌ای اعتبارسنجی کنی."]],
  },
  {
    id: "react-b7", t: "کامپوننت‌های شرطی",
    p: "رندر شرطی با && و ternary انجام می‌شود؛ دانستن تفاوت‌شان از رندر شدن 0 یا null ناخواسته جلوگیری می‌کند.",
    pts: ["count && <div/> اگر count صفر باشد، خود ۰ را رندر می‌کند!", "ternary برای دو حالت و null برای پنهان‌کردن", "شرط را بیرون JSX به متغیر boolean تبدیل کن"],
    code: ["tsx", "cond.tsx", "// خطرناک: اگر count=0 باشد، عدد 0 چاپ می‌شود!\n{count && <Badge />}\n\n// درست:\n{count > 0 && <Badge />}\n{isLoggedIn ? <Profile /> : <Login />}"],
    warn: "0 و NaN و '' در JS falsy‌اند ولی React عدد ۰ را رندر می‌کند؛ همیشه شرط را boolean کن (مثل count > 0).",
    q: [["چرا {count && <Badge/>} ممکن است عدد ۰ نشان دهد؟", ["باگ React", "چون ۰ falsy است ولی React آن را به‌عنوان متن رندر می‌کند؛ && مقدار چپ را برمی‌گرداند", "ممکن نیست", "برای خطا"], 1, "وقتی چپِ && falsy باشد، همان مقدار چپ (۰) برگردانده و رندر می‌شود؛ پس شرط را به boolean تبدیل کن."]],
  },
  {
    id: "react-b8", t: "Custom Hook و استفاده‌مجدد",
    p: "Custom Hook تابعی است که با use شروع می‌شود و منطق stateدار را قابل‌استفاده‌مجدد می‌کند؛ راه اصلی اشتراک منطق بین کامپوننت‌هاست.",
    pts: ["نام باید با use شروع شود تا قوانین Hook چک شوند", "هر فراخوان Hook، state جداگانه خودش را دارد", "useLocalStorage و useFetch نمونه‌های رایج‌اند"],
    code: ["tsx", "hook.tsx", "function useToggle(initial = false) {\n  const [on, setOn] = useState(initial);\n  const toggle = () => setOn(o => !o);\n  return [on, toggle] as const;\n}\n\nconst [dark, toggleDark] = useToggle();"],
    q: [["اگر دو کامپوننت از یک Custom Hook استفاده کنند، state‌شان مشترک است؟", ["بله", "خیر — هر فراخوان state کاملاً جدا دارد", "بستگی دارد", "گاهی"], 1, "Hook فقط منطق را به اشتراک می‌گذارد نه state را؛ هر کامپوننت نمونه مستقل خودش را دارد."]],
  },
  {
    id: "react-b9", t: "Context برای داده سراسری",
    p: "Context داده را بدون پاس‌دادن props از درخت عبور می‌دهد؛ برای تم، زبان و کاربر لاگین عالی است ولی برای داده پرتغییر، رندر اضافی می‌آورد.",
    pts: ["createContext + Provider + useContext سه‌گانه است", "هر تغییر Context همه مصرف‌کننده‌ها را رندر می‌کند", "برای state پویا، Zustand یا React Query بهتر است"],
    code: ["tsx", "context.tsx", "const ThemeCtx = createContext<'light' | 'dark'>('light');\n\nfunction App() {\n  return (\n    <ThemeCtx.Provider value=\"dark\">\n      <Toolbar />\n    </ThemeCtx.Provider>\n  );\n}\nconst theme = useContext(ThemeCtx);"],
    q: [["Context برای چه داده‌ای مناسب نیست؟", ["تم صفحه", "داده‌ای که هر ثانیه تغییر می‌کند، چون همه مصرف‌کننده‌ها رندر می‌شوند", "زبان", "کاربر لاگین"], 1, "تغییر Context همه subscriberها را رندر می‌کند؛ برای داده پرتغییر، راه‌حل‌های با subscribe انتخابی بهترند."]],
  },
  {
    id: "react-b10", t: "React.memo و useMemo",
    p: "memo کامپوننت را از رندر با props یکسان بازمی‌دارد و useMemo نتیجه محاسبه گران را کش می‌کند؛ ولی استفاده نابجا خودش سربار است.",
    pts: ["memo فقط وقتی props مرجع یکسان باشند جلوی رندر را می‌گیرد", "useMemo برای محاسبات گران و مراجع پایدار", "useCallback تابع پایدار برای پاس‌دادن به memo می‌سازد"],
    code: ["tsx", "memo.tsx", "const Row = memo(function Row({ item }: { item: Item }) {\n  return <tr>{item.name}</tr>;\n});\n\nconst sorted = useMemo(\n  () => [...items].sort((a, b) => a.name.localeCompare(b.name)),\n  [items]\n);"],
    tip: "اول با Profiler ببین چه چیزی واقعاً زیاد رندر می‌شود؛ ۹۰٪ memoها و useCallbackها بدون اندازه‌گیری، سربار اضافه می‌کنند نه کاهش.",
    q: [["چرا memo همیشه جلوی رندر را نمی‌گیرد؟", ["باگ است", "چون اگر props مرجع جدید باشند (مثل آبجکت ساخته‌شده در رندر)، مقایسه ناموفق است", "کند است", "ممکن نیست"], 1, "memo با مقایسه سطحی props کار می‌کند؛ آبجکت/تابع ساخته‌شده در هر رندر، مرجع جدید است و مقایسه شکست می‌خورد."]],
  },
  {
    id: "react-b11", t: "مدیریت خطا با Error Boundary",
    p: "Error Boundary کامپوننتی کلاسی است که خطای رندر زیردرختش را می‌گیرد و UI جایگزین نشان می‌دهد؛ بدون آن، یک خطا کل اپ را سفید می‌کند.",
    pts: ["با componentDidCatch و getDerivedStateFromError پیاده می‌شود", "خطای event handler را نمی‌گیرد، فقط رندر را", "هر بخش مهم اپ را با boundary جدا محافظت کن"],
    code: ["tsx", "boundary.tsx", "class Boundary extends Component<{}, { err: boolean }> {\n  state = { err: false };\n  static getDerivedStateFromError() {\n    return { err: true };\n  }\n  render() {\n    return this.state.err\n      ? <p>چیزی اشتباه شد!</p>\n      : this.props.children;\n  }\n}"],
    q: [["Error Boundary چه خطاهایی را نمی‌گیرد؟", ["خطای رندر", "خطای event handler و کد ناهمزمان و خطای خودش", "هیچ‌کدام", "همه را می‌گیرد"], 1, "boundary فقط خطاهای رندر زیردرخت را می‌گیرد؛ برای handlerها باید try/catch جدا داشته باشی."]],
  },
  {
    id: "react-b12", t: "معماری کامپوننت و پوشه‌بندی",
    p: "معماری خوب کامپوننت، نمایشی و کانتینری را جدا می‌کند و بر اساس فیچر پوشه می‌سازد نه بر اساس نوع فایل؛ مقیاس‌پذیری از اینجا شروع می‌شود.",
    pts: ["کامپوننت نمایشی فقط props می‌گیرد و state ندارد", "کانتینری داده را می‌گیرد و به نمایشی می‌دهد", "پوشه‌بندی فیچرمحور: features/orders به‌جای components/"],
    code: ["txt", "ساختار پروژه", "src/\n  features/\n    orders/\n      OrdersPage.tsx\n      OrderList.tsx\n      useOrders.ts\n  components/      ← مشترک و نمایشی\n    Button.tsx\n  hooks/"],
    tip: "قانون طلایی: اگر کامپوننتی را نمی‌توانی در جای دیگر اپ استفاده کنی، باید داخل پوشه فیچرش باشد نه components مشترک.",
    q: [["تفاوت کامپوننت نمایشی و کانتینری چیست؟", ["اندازه‌شان", "نمایشی فقط props می‌گیرد و ظاهر است؛ کانتینری منطق و داده را مدیریت می‌کند", "سرعت‌شان", "تعداد props"], 1, "این جداسازی باعث می‌شود UI قابل‌استفاده‌مجدد و منطق قابل‌تست باشد."]],
  },
];

/* ================= Node.js — ۱۲ درس ================= */
const NODE: LSpec[] = [
  {
    id: "node-b1", t: "Event Loop در عمل",
    p: "Event Loop به Node اجازه می‌دهد با یک thread همزمان هزاران اتصال را مدیریت کند؛ عملیات‌های I/O را به سیستم‌عامل می‌سپارد و با callback برمی‌گردد.",
    pts: ["Node تک‌thread است ولی I/O خارج از آن انجام می‌شود", "میکروتسک‌ها (Promise) قبل از ماکروتسک‌ها (setTimeout) اجرا می‌شوند", "کد مسدودکننده حلقه را قفل و همه را معطل می‌کند"],
    code: ["js", "loop.js", "console.log('۱');\nsetTimeout(() => console.log('۲'), 0);\nPromise.resolve().then(() => console.log('۳'));\nconsole.log('۴');\n// خروجی: ۱ ، ۴ ، ۳ ، ۲"],
    q: [["چرا setTimeout با تاخیر ۰، بعد از Promise اجرا می‌شود؟", ["باگ", "چون Promise میکروتسک است و صف آن قبل از ماکروتسکِ setTimeout خالی می‌شود", "تصادفی", "بستگی به CPU"], 1, "Event Loop بعد از هر تسک، اول کل صف میکروتسک‌ها را خالی می‌کند؛ Promise در میکروتسک و setTimeout در ماکروتسک است."]],
  },
  {
    id: "node-b2", t: "ماژول‌ها و package.json",
    p: "Node با CommonJS (require) و ES Modules (import) ماژول‌ها را سازمان می‌دهد؛ package.json شناسنامه پروژه و node_modules خانه وابستگی‌هاست.",
    pts: ["type: module در package.json یعنی ESM", "dependencies برای تولید و devDependencies برای توسعه", "npm install بدون آرگومان همه را از lockfile نصب می‌کند"],
    code: ["js", "package.json", "{\n  \"name\": \"app\",\n  \"type\": \"module\",\n  \"scripts\": { \"start\": \"node index.js\" },\n  \"dependencies\": { \"express\": \"^4.18.0\" },\n  \"devDependencies\": { \"nodemon\": \"^3.0.0\" }\n}"],
    q: [["تفاوت dependencies و devDependencies چیست؟", ["هیچ", "dependencies برای اجرای تولید لازم است؛ devDependencies فقط برای توسعه و تست", "نسخه‌شان", "سرعت نصب"], 1, "در سرور تولید، npm install --omit=dev فقط dependencies را نصب می‌کند تا سبک بماند."]],
  },
  {
    id: "node-b3", t: "ساخت REST API با Express",
    p: "Express حداقل‌گراترین فریم‌ورک Node برای ساخت API است؛ با routeها و middleware یک سرور کامل می‌سازی و قرارداد REST مسیر و فعل HTTP را معنادار می‌کند.",
    pts: ["GET خواندن، POST ساختن، PUT/PATCH به‌روزرسانی، DELETE حذف", "app.use برای middleware سراسری و app.get برای مسیر", "کد وضعیت پیام می‌دهد: ۲۰۰ موفق، ۲۰۱ ساخته‌شد، ۴۰۴ نیست، ۵۰۰ خطا"],
    code: ["js", "api.js", "import express from 'express';\nconst app = express();\napp.use(express.json());\n\napp.get('/users', (req, res) => res.json(users));\napp.post('/users', (req, res) => {\n  const u = { id: users.length + 1, ...req.body };\n  users.push(u);\n  res.status(201).json(u);\n});\napp.listen(3000);"],
    q: [["بعد از POST موفق چه کد وضعیتی مناسب است؟", ["۲۰۰", "۲۰۱ ساخته‌شد", "۴۰۴", "۳۰۲"], 1, "201 Created به معنی منبع جدید ساخته‌شده است و معمولاً با Location و بدنه منبع جدید برمی‌گردد."]],
  },
  {
    id: "node-b4", t: "Middleware و ترتیب اجرا",
    p: "هر درخواست در Express از زنجیره middleware می‌گذرد؛ هر کدام می‌تواند درخواست را تغییر دهد، پاسخ بدهد یا با next() به بعدی بسپارد — ترتیب ثبت، ترتیب اجراست.",
    pts: ["next() را فراموش کنی، درخواست همان‌جا می‌ماند", "middleware خطا ۴ پارامتر دارد: (err, req, res, next)", "app.use ترتیب را تعیین می‌کند؛ auth قبل از routeها"],
    code: ["js", "mw.js", "app.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next();\n});\n\napp.use((err, req, res, next) => {\n  res.status(500).json({ error: 'خطای داخلی' });\n});"],
    q: [["اگر middleware‌ای next() را صدا نزند چه می‌شود؟", ["خطای ۵۰۰", "درخواست همان‌جا می‌ماند تا client timeout شود؛ پاسخی نمی‌رود", "به بعدی می‌رود", "کرش می‌کند"], 1, "زنجیره فقط با next() جلو می‌رود؛ بدون آن نه پاسخی ارسال می‌شود نه middleware بعدی اجرا می‌شود."]],
  },
  {
    id: "node-b5", t: "کار با دیتابیس و SQL",
    p: "اتصال Node به دیتابیس با درایور یا ORM انجام می‌شود؛ همیشه از query پارامتری‌شده استفاده کن تا از SQL injection در امان باشی.",
    pts: ["pool اتصال‌ها را نگه می‌دارد تا هر query اتصال نسازد", "query پارامتری‌شده: db.query('SELECT ... WHERE id=$1', [id])", "ORM مثل Prisma نوع و مهاجرت را مدیریت می‌کند"],
    code: ["js", "db.js", "import pg from 'pg';\nconst pool = new pg.Pool({ connectionString: process.env.DB_URL });\n\napp.get('/users/:id', async (req, res) => {\n  const { rows } = await pool.query(\n    'SELECT * FROM users WHERE id = $1', [req.params.id]);\n  res.json(rows[0]);\n});"],
    warn: "ساخت query با اتصال رشته (SELECT * FROM users WHERE id = ' + id) یعنی دعوت از SQL injection؛ همیشه پارامتری‌شده.",
    q: [["چرا query پارامتری‌شده امن است؟", ["کوتاه‌تر است", "چون مقادیر جدا از ساختار فرمان به دیتابیس می‌روند و به‌عنوان داده تفسیر می‌شوند", "سریع‌تر است", "کش می‌شود"], 1, "در query پارامتری، ورودی کاربر هرگز بخشی از ساختار SQL نمی‌شود؛ پس نمی‌تواند فرمان تزریق کند."]],
  },
  {
    id: "node-b6", t: "اعتبارسنجی ورودی",
    p: "هرگز به ورودی client اعتماد نکن؛ اعتبارسنجی باید در سرور انجام شود حتی اگر فرانت هم چک کند، چون فرانت قابل‌دورزدن است.",
    pts: ["کتابخانه‌هایی مثل zod هم نوع می‌دهند هم اعتبارسنجی", "در سرور همیشه نوع، بازه و طول را چک کن", "پیام خطای مشخص ولی بدون افشای جزئیات داخلی"],
    code: ["js", "validate.js", "import { z } from 'zod';\nconst UserSchema = z.object({\n  name: z.string().min(2).max(50),\n  age: z.number().int().min(0).max(120),\n  email: z.string().email(),\n});\n\napp.post('/users', (req, res) => {\n  const parsed = UserSchema.safeParse(req.body);\n  if (!parsed.success)\n    return res.status(400).json({ error: parsed.error.issues });\n  /* ادامه با parsed.data */\n});"],
    q: [["چرا اعتبارسنجی فقط در فرانت کافی نیست؟", ["کافی است", "چون client قابل‌کنترل است و هرکس می‌تواند درخواست خام بفرستد", "فرانت کند است", "CSS خراب می‌شود"], 1, "فرانت فقط برای تجربه کاربری چک می‌کند؛ مهاجم مستقیم به API درخواست می‌فرستد، پس سرور باید خودش اعتبارسنجی کند."]],
  },
  {
    id: "node-b7", t: "احراز هویت با JWT",
    p: "JWT توکنی امضاشده است که ادعاها را حمل می‌کند؛ سرور فقط امضا را چک می‌کند. دسترسی کوتاه‌عمر و refresh در کوکی HttpOnly الگوی امن است.",
    pts: ["jwt.sign ادعاها را با secret امضا می‌کند", "توکن را در هدر Authorization: Bearer بفرست", "secret را در متغیر محیطی نگه دار، نه کد"],
    code: ["js", "jwt.js", "import jwt from 'jsonwebtoken';\n\nconst token = jwt.sign(\n  { sub: user.id, role: user.role },\n  process.env.SECRET,\n  { expiresIn: '15m' });\n\n// middleware:\nconst payload = jwt.verify(req.headers.authorization?.split(' ')[1], process.env.SECRET);"],
    q: [["چرا JWT را نباید در localStorage نگه داشت؟", ["کند است", "چون هر اسکریپت صفحه (از جمله XSS) می‌تواند آن را بخواند؛ کوکی HttpOnly امن‌تر است", "جا نمی‌شود", "مرورگر پاک می‌کند"], 1, "localStorage در دسترس همه جاوااسکریپت‌های صفحه است؛ یک XSS ساده توکن را می‌دزدد. کوکی HttpOnly از JS پنهان است."]],
  },
  {
    id: "node-b8", t: "کد ناهمزمان و async/await",
    p: "async/await سینتکس خوانای Promise است؛ await فقط داخل تابع async و برای مدیریت خطا از try/catch استفاده می‌شود.",
    pts: ["تابع async همیشه Promise برمی‌گرداند", "برای عملیات مستقل از Promise.all استفاده کن نه await پشت‌سرهم", "try/catch دور await، خطا را می‌گیرد"],
    code: ["js", "async.js", "// کند: سریالی — ۳ ثانیه\nconst a = await fetchA();\nconst b = await fetchB();\n\n// سریع: موازی — ۲ ثانیه (اگر هرکدام ۲s)\nconst [x, y] = await Promise.all([fetchA(), fetchB()]);"],
    q: [["چرا Promise.all برای عملیات مستقل سریع‌تر است؟", ["کش دارد", "چون همه همزمان شروع می‌شوند و مجموع زمان = کندترین، نه جمع زمان‌ها", "موازی روی CPU", "کمتر کد است"], 1, "await پشت‌سرهم هر عملیات را منتظر قبلی می‌کند؛ Promise.all همه را همزمان شروع می‌کند."]],
  },
  {
    id: "node-b9", t: "استریم‌ها و فایل‌های بزرگ",
    p: "استریم داده را تکه‌تکه می‌خواند و می‌نویسد؛ برای فایل‌های بزرگ حافظه را O(1) نگه می‌دارد به‌جای خواندن کل فایل در RAM.",
    pts: ["createReadStream فایل را تکه‌تکه می‌خواند", "pipe() خروجی یک استریم را به ورودی دیگری وصل می‌کند", "برای دانلود/آپلود بزرگ همیشه استریم، نه readFile"],
    code: ["js", "stream.js", "import fs from 'fs';\n\n// کل فایل در RAM — بد برای فایل بزرگ:\n// fs.readFile('big.mp4', cb);\n\n// استریم — حافظه ثابت:\nfs.createReadStream('big.mp4')\n  .pipe(fs.createWriteStream('copy.mp4'));"],
    q: [["چرا استریم برای فایل بزرگ بهتر از readFile است؟", ["سریع‌تر می‌خواند", "چون داده را تکه‌تکه پردازش می‌کند و حافظه ثابت می‌ماند نه اندازه فایل", "فشرده می‌کند", "اجباری است"], 1, "readFile کل فایل را یک‌جا در RAM می‌آورد؛ استریم با بافر کوچک ثابت، هر مقدار فایل را پردازش می‌کند."]],
  },
  {
    id: "node-b10", t: "مدیریت خطای سراسری",
    p: "خطاهای sync را با middleware چهارپارامتره و خطاهای async را با wrapper بگیر تا هیچ خطایی سرور را نگیرد؛ Node با خطای نگرفته‌شده می‌تواند کرش کند.",
    pts: ["در handlerهای async از asyncHandler wrapper استفاده کن", "process.on('unhandledRejection') تور آخر است، نه راه‌حل", "همیشه به خطا پاسخ بده وگرنه client می‌ماند"],
    code: ["js", "err.js", "const asyncHandler = fn => (req, res, next) =>\n  Promise.resolve(fn(req, res, next)).catch(next);\n\napp.get('/orders', asyncHandler(async (req, res) => {\n  res.json(await db.orders());\n}));\n\napp.use((err, req, res, next) =>\n  res.status(500).json({ error: 'خطا' }));"],
    q: [["چرا بدون wrapper، خطای handler ناهمزمان به middleware خطا نمی‌رسد؟", ["می‌رسد", "چون Express خطاهای async را نمی‌بیند؛ باید با catch به next پاس داده شوند", "Node نمی‌فهمد", "بستگی دارد"], 1, "Express فقط خطاهای sync و next(err) را می‌گیرد؛ Promise reject‌شده باید با .catch(next) به زنجیره برگردد."]],
  },
  {
    id: "node-b11", t: "متغیرهای محیطی و پیکربندی",
    p: "تنظیمات حساس و وابسته به محیط را در متغیر محیطی نگه دار نه کد؛ با dotenv در توسعه و با محیط واقعی در تولید، همان ۱۲-Factor.",
    pts: [".env را هرگز commit نکن — در .gitignore باشد", "process.env.DB_URL در کد خوانده می‌شود", "برای هر محیط (dev/prod) مقادیر جدا"],
    code: ["js", "env.js", "import 'dotenv/config';\n\nconst config = {\n  port: process.env.PORT || 3000,\n  dbUrl: process.env.DB_URL,\n  secret: process.env.JWT_SECRET,\n};\n\nif (!config.dbUrl) throw new Error('DB_URL لازم است');\nexport default config;"],
    warn: "commit کردن .env یعنی افشای رمزها در تاریخچه git — حتی اگر بعد پاکش کنی، در تاریخچه می‌ماند و باید rotate شوند.",
    q: [["چرا نباید secret را در کد گذاشت؟", ["کند است", "چون کد به ریپازیتوری و دست همه می‌رسد؛ متغیر محیطی جدا از کد توزیع می‌شود", "جا نمی‌شود", "Node نمی‌خواند"], 1, "کد عمومی یا قابل‌دسترسی است؛ راز باید خارج از کد، در محیط اجرا تزریق شود تا لو نرود."]],
  },
  {
    id: "node-b12", t: "تست API با Supertest",
    p: "API را با supertest بدون بالاآوردن شبکه تست می‌کنی؛ app را می‌گیری و درخواست‌ها را شبیه‌سازی می‌کنی — تست سریع و قابل‌اتکا.",
    pts: ["supertest(app).get('/users') بدون listen", "کد وضعیت و بدنه را assert کن", "برای هر تست دیتابیس را جدا یا پاک کن"],
    code: ["js", "api.test.js", "import request from 'supertest';\nimport app from './app.js';\n\nit('لیست کاربران برمی‌گرداند', async () => {\n  const res = await request(app).get('/users');\n  expect(res.status).toBe(200);\n  expect(Array.isArray(res.body)).toBe(true);\n});"],
    tip: "app را از listen جدا export کن تا هم سرور اصلی استفاده کند هم تست — این جداسازی کوچک، تست‌پذیری کل API را می‌سازد.",
    q: [["مزیت supertest چیست؟", ["سریع‌تر از fetch", "بدون بازکردن پورت واقعی، مستقیم به app درخواست می‌زند و تست را ایزوله می‌کند", "UI را تست می‌کند", "دیتابیس می‌سازد"], 1, "supertest handlerهای Express را مستقیم صدا می‌زند؛ پس تست بدون درگیری پورت و شبکه اجرا می‌شود."]],
  },
];

/* ================= SQL — ۱۲ درس ================= */
const SQL: LSpec[] = [
  {
    id: "sql-b1", t: "SELECT و فیلتر با WHERE",
    p: "SELECT پایه همه پرس‌وجوهاست؛ WHERE ردیف‌ها را فیلتر می‌کند و ترتیب نوشتن با ترتیب اجرا فرق دارد — اول FROM و WHERE، بعد SELECT.",
    pts: ["SELECT * همه ستون‌ها؛ بهتر است نام ببري", "AND و OR و NOT ترکیب شرط‌ها؛ پرانتز برای اولویت", "LIKE برای الگو و IN برای چند مقدار"],
    code: ["sql", "select.sql", "SELECT name, price\nFROM products\nWHERE price > 100\n  AND category IN ('برق', 'کامپیوتر')\n  AND name LIKE '%لپ%'\nORDER BY price DESC\nLIMIT 10;"],
    q: [["ترتیب اجرای واقعی یک SELECT چیست؟", ["همان ترتیب نوشتن", "FROM → WHERE → SELECT → ORDER BY → LIMIT", "SELECT اول", "LIMIT اول"], 1, "دیتابیس اول منبع و فیلتر را تعیین می‌کند، بعد ستون‌ها را برمی‌دارد و در آخر مرتب و محدود می‌کند."]],
  },
  {
    id: "sql-b2", t: "JOIN و انواع آن",
    p: "JOIN ردیف‌های دو جدول را بر اساس ستون مشترک ترکیب می‌کند؛ INNER فقط مشترک‌ها، LEFT همه چپ‌ها و RIGHT همه راست‌ها را نگه می‌دارد.",
    pts: ["INNER JOIN فقط ردیف‌های دارای تطابق در هر دو", "LEFT JOIN همه چپ + تطابق‌های راست (یا NULL)", "همیشه نام جدول بده: orders.user_id = users.id"],
    code: ["sql", "join.sql", "-- سفارش‌های هر کاربر با نامش:\nSELECT u.name, o.total\nFROM users u\nJOIN orders o ON o.user_id = u.id;\n\n-- همه کاربران حتی بدون سفارش:\nSELECT u.name, COUNT(o.id) AS orders\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nGROUP BY u.id, u.name;"],
    q: [["تفاوت INNER و LEFT JOIN چیست؟", ["سرعت", "INNER فقط مشترک‌ها؛ LEFT همه ردیف‌های جدول چپ را حتی بدون تطابق نگه می‌دارد", "هیچ", "جهت جدول"], 1, "در LEFT JOIN ردیف‌های چپ که تطابق ندارند هم می‌مانند و ستون‌های راستشان NULL می‌شود."]],
  },
  {
    id: "sql-b3", t: "GROUP BY و توابع تجمیعی",
    p: "GROUP BY ردیف‌ها را دسته‌بندی و توابع تجمیعی مثل COUNT و SUM را روی هر دسته اعمال می‌کند؛ HAVING فیلترِ بعد از گروه‌بندی است.",
    pts: ["هر ستون غیرتجمیعی در SELECT باید در GROUP BY باشد", "WHERE قبل از گروه‌بندی، HAVING بعد از آن فیلتر می‌کند", "COUNT(*) تعداد ردیف و SUM جمع مقدار"],
    code: ["sql", "group.sql", "SELECT category, COUNT(*) AS n, AVG(price) AS avg_p\nFROM products\nGROUP BY category\nHAVING COUNT(*) > 5\nORDER BY avg_p DESC;"],
    q: [["تفاوت WHERE و HAVING چیست؟", ["هیچ", "WHERE قبل از گروه‌بندی ردیف فیلتر می‌کند؛ HAVING بعد از GROUP BY روی دسته‌ها", "سینتکس", "سرعت"], 1, "WHERE نمی‌تواند روی نتیجه تجمیع فیلتر کند چون قبل از گروه‌بندی اجرا می‌شود؛ HAVING برای شرط روی دسته‌هاست."]],
  },
  {
    id: "sql-b4", t: "INSERT، UPDATE و DELETE",
    p: "این سه فرمان داده را تغییر می‌دهند؛ مهم‌ترین اصل: UPDATE و DELETE را همیشه اول با WHERE دقیق تست کن و هیچ‌وقت بدون WHERE ننویس.",
    pts: ["INSERT INTO t (a,b) VALUES (1,2) درج می‌کند", "UPDATE بدون WHERE همه ردیف‌ها را عوض می‌کند!", "در تراکنش بنویس تا قابل بازگشت باشد"],
    code: ["sql", "dml.sql", "BEGIN;\nUPDATE products SET price = price * 1.1\nWHERE category = 'برق';\n-- اگر اشتباه بود:\nROLLBACK;\n-- اگر درست بود:\nCOMMIT;"],
    warn: "UPDATE products SET price=0 بدون WHERE کل جدول را صفر می‌کند — همیشه اول با SELECT همان WHERE تعداد ردیف‌های موثر را چک کن.",
    q: [["چرا UPDATE/DELETE بدون WHERE خطرناک است؟", ["کند است", "چون روی همه ردیف‌های جدول اعمال می‌شود و می‌تواند کل داده را خراب کند", "خطا می‌دهد", "اجرا نمی‌شود"], 1, "بدون WHERE شرطی نیست که ردیف‌ها را محدود کند؛ فرمان به تک‌تک ردیف‌ها اعمال می‌شود."]],
  },
  {
    id: "sql-b5", t: "طراحی اسکیما و کلید",
    p: "طراحی خوب اسکیما با کلید اولیه برای یکتایی، کلید خارجی برای رابطه و تایپ درست برای هر ستون شروع می‌شود؛ اینجا کیفیت داده متولد می‌شود.",
    pts: ["PRIMARY KEY یکتا و غیرNULL است", "FOREIGN KEY ارجاع به ردیف معتبر جدول دیگر را تضمین می‌کند", "برای شناسه از SERIAL/BIGINT و برای متن از طول مناسب"],
    code: ["sql", "schema.sql", "CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  email TEXT UNIQUE NOT NULL,\n  created_at TIMESTAMPTZ DEFAULT now()\n);\n\nCREATE TABLE orders (\n  id SERIAL PRIMARY KEY,\n  user_id INT NOT NULL REFERENCES users(id),\n  total NUMERIC(10,2)\n);"],
    q: [["نقش FOREIGN KEY چیست؟", ["سرعت", "تضمین می‌کند مقدار به یک ردیف موجود در جدول دیگر اشاره کند و رابطه سالم بماند", "رمزنگاری", "مرتب‌سازی"], 1, "FOREIGN KEY از ردیف‌های یتیم جلوگیری می‌کند؛ نمی‌توانی سفارشی با user_id ناموجود بسازی."]],
  },
  {
    id: "sql-b6", t: "نرمال‌سازی و فرم‌های نرمال",
    p: "نرمال‌سازی تکرار داده را با تقسیم جدول حذف می‌کند؛ تا فرم سوم، هر واقعیت فقط یک‌جا ذخیره می‌شود و ناهنجاری به‌روزرسانی از بین می‌رود.",
    pts: ["فرم اول: ستون‌های اتمی و بدون گروه تکراری", "فرم دوم: وابستگی کامل به کل کلید اولیه", "فرم سوم: بدون وابستگی به ستون غیرکلید"],
    code: ["sql", "normalize.sql", "-- غیرنرمال: نام مشتری در هر سفارش تکرار\n-- orders(id, customer_name, total)\n\n-- نرمال: مشتری یک‌جا، سفارش ارجاع\n-- customers(id, name)\n-- orders(id, customer_id, total)"],
    q: [["مشکل اصلی ذخیره نام مشتری در جدول سفارش چیست؟", ["کند است", "تکرار و ناهنجاری: تغییر نام باید در همه سفارش‌های آن مشتری اعمال شود", "جا می‌گیرد", "ممکن نیست"], 1, "اگر نام در هزار سفارش تکرار شده، یک تغییر نام باید هزار ردیف را به‌روز کند و ممکن است ناسازگار شود."]],
  },
  {
    id: "sql-b7", t: "ایندکس و سرعت پرس‌وجو",
    p: "ایندکس ساختار مرتبی است که جست‌وجو را از اسکن کامل O(n) به O(log n) می‌رساند؛ ولی هر ایندکس نوشتن را کمی کندتر می‌کند.",
    pts: ["روی ستون‌های WHERE و JOIN ایندکس بزن", "ایندکس زیاد، INSERT/UPDATE را کند می‌کند", "با EXPLAIN ببین آیا ایندکس واقعاً استفاده شد"],
    code: ["sql", "index.sql", "CREATE INDEX idx_orders_user ON orders(user_id);\n\nEXPLAIN ANALYZE\nSELECT * FROM orders WHERE user_id = 42;\n-- دنبال 'Index Scan' باش نه 'Seq Scan'"],
    q: [["چرا ایندکس، نوشتن را کندتر می‌کند؟", ["قفل می‌گذارد", "چون با هر INSERT/UPDATE ساختار ایندکس هم باید به‌روز بماند", "رمزنگاری می‌کند", "نمی‌کند"], 1, "ایندکس یک کپی مرتب از ستون است؛ تغییر داده یعنی حفظ ترتیب آن کپی هم."]],
  },
  {
    id: "sql-b8", t: "تراکنش و ACID",
    p: "تراکنش چند عمل را یک واحد اتمی می‌کند: یا همه انجام می‌شوند یا هیچ‌کدام — برای انتقال پول و هر عملیات چندمرحله‌ای حیاتی است.",
    pts: ["BEGIN شروع، COMMIT تایید، ROLLBACK بازگشت", "Atomicity یعنی همه یا هیچ", "Isolation یعنی تراکنش‌ها مزاحم هم نمی‌شوند"],
    code: ["sql", "tx.sql", "BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;   -- هر دو یا هیچ‌کدام"],
    q: [["اگر وسط تراکنش انتقال پول، برق برود چه می‌شود؟", ["پول نصف منتقل می‌شود", "هیچ‌کدام اعمال نمی‌شود چون تا COMMIT نهایی نشده و بازگردانده می‌شود", "دوباره اجرا می‌شود", "دیتابیس خراب می‌شود"], 1, "تا COMMIT، تغییرات موقتی‌اند؛ با خرابی، کل تراکنش به حالت قبل برمی‌گردد — خاصیت Atomicity."]],
  },
  {
    id: "sql-b9", t: "زیرپرس‌وجو و EXISTS",
    p: "زیرپرس‌وجو، پرس‌وجویی داخل پرس‌وجوی دیگر است؛ EXISTS برای بررسی وجود معمولاً از IN با لیست بزرگ کارآمدتر است.",
    pts: ["زیرپرس‌وجو می‌تواند در WHERE، SELECT یا FROM باشد", "EXISTS به‌محض یافتن اولین تطابق متوقف می‌شود", "برای مقایسه با مجموعه از ANY و ALL استفاده کن"],
    code: ["sql", "subquery.sql", "-- کاربرانی که حداقل یک سفارش دارند:\nSELECT name FROM users u\nWHERE EXISTS (\n  SELECT 1 FROM orders o WHERE o.user_id = u.id\n);"],
    q: [["چرا EXISTS اغلب از IN بهتر است؟", ["کوتاه‌تر است", "چون به‌محض یافتن اولین تطابق متوقف می‌شود و نیاز به ساخت کل لیست ندارد", "همیشه", "کش دارد"], 1, "IN ممکن است کل نتیجه زیرپرس‌وجو را بسازد؛ EXISTS فقط وجود را چک می‌کند و زود برمی‌گردد."]],
  },
  {
    id: "sql-b10", t: "توابع پنجره‌ای",
    p: "توابع پنجره‌ای روی گروهی از ردیف‌ها محاسبه می‌کنند بدون اینکه ردیف‌ها را جمع کنند — برای رتبه‌بندی، مجموع متحرک و مقایسه با قبلی.",
    pts: ["ROW_NUMBER و RANK رتبه می‌دهند", "SUM(x) OVER (PARTITION BY g ORDER BY t) مجموع تجمعی", "برخلاف GROUP BY، تعداد ردیف‌ها حفظ می‌شود"],
    code: ["sql", "window.sql", "-- رتبه هر فروشنده در گروهش:\nSELECT name, team, sales,\n  ROW_NUMBER() OVER (\n    PARTITION BY team ORDER BY sales DESC\n  ) AS rank_in_team\nFROM salespeople;"],
    q: [["تفاوت تابع پنجره‌ای با GROUP BY چیست؟", ["هیچ", "تابع پنجره‌ای ردیف‌ها را جمع نمی‌کند؛ روی هر ردیف، محاسبه‌ای روی گروهش نشان می‌دهد", "سرعت", "سینتکس"], 1, "GROUP BY ردیف‌ها را به یک ردیف خلاصه می‌کند؛ تابع پنجره‌ای همه ردیف‌ها را نگه می‌دارد و ستون محاسبه‌شده اضافه می‌کند."]],
  },
  {
    id: "sql-b11", t: "NoSQL و کی استفاده کنیم",
    p: "NoSQL برای داده‌های بدون اسکیمای ثابت، مقیاس افقی و مدل‌های سند/گراف است؛ ولی تراکنش و JOIN قوی SQL را ندارد — انتخاب بر اساس نیاز است.",
    pts: ["سند‌گرا (MongoDB) برای داده نیمه‌ساختار", "کلید-مقدار (Redis) برای کش و سرعت", "گراف (Neo4j) برای روابط عمیق مثل شبکه اجتماعی"],
    tab: [["معیار", "SQL", "NoSQL"], [["اسکیما", "ثابت و قوی", "انعطاف‌پذیر"], ["تراکنش", "ACID قوی", "معمولاً ضعیف‌تر"], ["مقیاس", "عمودی راحت‌تر", "افقی راحت‌تر"], ["رابطه", "JOIN قوی", "محدود"]]],
    q: [["کی SQL را به NoSQL ترجیح می‌دهی؟", ["همیشه", "وقتی تراکنش ACID و رابطه‌های پیچیده و اسکیمای مشخص نیاز داری", "هیچ‌وقت", "برای سرعت"], 1, "برای سیستم‌های مالی و هر جایی که سازگاری داده حیاتی است، SQL با ACID انتخاب امن‌تری است."]],
  },
  {
    id: "sql-b12", t: "مهاجرت اسکیما و نسخه‌بندی",
    p: "تغییر اسکیما در تولید با مهاجرت‌های نسخه‌بندی‌شده انجام می‌شود؛ هر تغییر یک فایل، قابل اجرا و قابل بازگشت — ابزارهایی مثل Flyway یا Prisma.",
    pts: ["هر مهاجرت شماره نسخه و دو مسیر up/down دارد", "ستون جدید را nullable اضافه کن تا قفل نشود", "تغییرهای بزرگ را چندمرحله‌ای کن"],
    code: ["sql", "migration.sql", "-- 002_add_phone.up.sql\nALTER TABLE users ADD COLUMN phone TEXT;\n\n-- 002_add_phone.down.sql\nALTER TABLE users DROP COLUMN phone;"],
    tip: "افزودن ستون NOT NULL به جدول بزرگ، جدول را قفل می‌کند؛ اول nullable اضافه کن، پر کن، بعد NOT NULL کن — سه مهاجرت کوچک و امن.",
    q: [["چرا مهاجرت‌ها را نسخه‌بندی می‌کنیم؟", ["برای زیبایی", "تا هر محیط دقیقاً همان تغییرات را به ترتیب بگیرد و تغییرات قابل بازگشت و ردیابی باشند", "اجباری نیست", "برای سرعت"], 1, "بدون نسخه‌بندی، اسکیمای dev و prod از هم جدا می‌شود و معلوم نیست چه تغییری کجا اعمال شده."]],
  },
];

export const BULK2: Record<string, Lesson[]> = {
  react: mkLs(REACT),
  node: mkLs(NODE),
  sql: mkLs(SQL),
};
