import type { Lesson } from "./content-types";

/* درس‌های تکمیلی جدید برای دوره‌ها */
export const EXTRA_LESSONS_C: Lesson[] = [
  {
    id: "py-x2",
    title: "Generator و Iterator — حافظه‌ی بی‌نهایت، مصرفِ اندک",
    minutes: 55,
    blocks: [
      { k: "p", t: "فرض کن یک فایل لاگ ۱۰ گیگابایتی داری و فقط خطاهایش را می‌خواهی. خواندن همه‌اش در یک لیست یعنی ۱۰ گیگابایت RAM — و کرش. Generator راه حل پایتون است: تابعی که به‌جای return از yield استفاده می‌کند و هر بار فقط «یک قلم» تولید می‌کند، بعد مکث می‌کند تا مصرف‌کننده بعدی را بخواهد. حافظه مصرفی: یکی. همین ایده پشت خط‌های پردازش داده پایتون است — حلقه‌ای که از روی میلیاردها رکورد می‌گذرد ولی هیچ‌وقت بیشتر از یک رکورد را نگه نمی‌دارد." },
      { k: "code", lang: "py", title: "generator.py", code: "import sys\n\n# لیست: همه‌چیز همین حالا در حافظه\nnums_list = [n * n for n in range(10_000_000)]\nprint(sys.getsizeof(nums_list))    # ≈ ۸۵ میلیون بایت!\n\n# Generator: همان داده، ولی «درخواستی»\nnums_gen = (n * n for n in range(10_000_000))\nprint(sys.getsizeof(nums_gen))     # ≈ ۱۰۰ بایت!\n\n# Generator واقعی با yield — پردازش فایل حجیم:\ndef errors(path):\n    with open(path, encoding='utf-8') as f:\n        for line in f:             # فایل هم خودش iterator است!\n            if 'ERROR' in line:\n                yield line.strip() # فقط خطاهای واقعی در حافظه‌اند\n\nfor line in errors('access.log'):\n    print(line)\n    # می‌توانی وسطش break کنی — بقیه فایل اصلاً خوانده نمی‌شود!" },
      { k: "def", term: "Protocol Iterator", t: "هر چیزی که متد __iter__ و __next__ داشته باشد، در for و همه ابزارهای پایتون کار می‌کند — از لیست و دیکشنری تا Generator و فایل باز. یعنی می‌توانی برای کلاس خودت تعریف کنی «پیمایش یعنی چه» و همه اکوسیستم پایتون بدون تغییر، رویش کار کند. Comprehension و * و zip و sum همه همین قرارداد کوچک را مصرف می‌کنند." },
      { k: "code", lang: "py", title: "pipeline.py", code: "# خط لوله تنبل — هر مرحله Generator، کل زنجیره یک‌عبوره:\ndef read_lines(path):\n    with open(path) as f:\n        yield from f\n\ndef parse(line):\n    parts = line.split()\n    return {'ip': parts[0], 'status': int(parts[8])}\n\ndef server_errors(rec):\n    return rec['status'] >= 500\n\npipeline = filter(server_errors, map(parse, read_lines('access.log')))\nfirst_5 = list(itertools.islice(pipeline, 5))   # فقط ۵ تا پردازش شد!" },
      { k: "table", head: ["", "لیست", "Generator"], rows: [["حافظه", "O(n) — همه در RAM", "O(1) — یکی در لحظه"], ["سرعت شروع", "باید همه ساخته شود", "فوری"], ["پیمایش دوم", "ممکن", "تمام‌شدنی — دوباره بساز"], ["اینکس‌گذاری", "lst[100]", "ممکن نیست"], ["مناسب", "داده کوچک با استفاده مکرر", "جریان‌های بزرگ یا بی‌پایان"]] },
      { k: "tip", title: "نکته منتور", t: "yield from را یاد بگیر — وقتی یک Generator می‌خواهد خروجی Generator دیگری را «رد کند»، یک خط جایگزین حلقه for می‌شود و ساختن Pipelineهای چندلایه را خوانا نگه می‌دارد. و itertools (islice، chain، groupby) کتابخانه‌ای است که Generatorها را به ابزار صنعتی تبدیل می‌کند." },
    ],
    quiz: [
      { q: "چرا Generator روی فایل ۱۰ گیگابایتی کار می‌کند ولی لیست نه؟", opts: ["چون فشرده‌سازی می‌کند", "چون داده را درخواستی و یکی‌یکی تولید می‌کند — حافظه O(1) می‌ماند", "چون دیسک سریع‌تر است", "چون موازی است"], ans: 1, why: "yield بعد از هر قلم متوقف می‌شود؛ مصرف‌کننده بعدی را بخواهد تا قلم بعدی ساخته شود. هیچ‌وقت کل مجموعه در RAM وجود ندارد." },
      { q: "Generator تمام‌شده چه ویژگی‌ای دارد؟", opts: ["دوباره از اول شروع می‌شود", "یک‌بار مصرف است؛ پیمایش دوم خالی است — باید دوباره ساخته شود", "کش می‌شود", "خطا می‌دهد"], ans: 1, why: "Generator وضعیت پیمایش را نگه می‌دارد و به انتها که برسد، StopIteration می‌دهد؛ برعکس لیست که هر بار از نو پیمایش می‌شود." },
    ],
  },
  {
    id: "cpp-x1",
    title: "Move Semantics و Template — سرعت بدون کپی",
    minutes: 60,
    blocks: [
      { k: "p", t: "سوال بزرگ C++: چطور آبجکت‌های بزرگ (بردار میلیونی) را بین توابع جابه‌جا کنیم بدون کپی؟ جواب C++11 شاهکار است: Move Semantics. وقتی آبجکتی «موقت» است و دیگر کسی لازمش ندارد (مثل مقدار برگشتی تابع)، به‌جای کپی‌کردن داده‌هایش، «داخلی‌هایش را می‌دزدیم»: اشاره‌گر به بافر منتقل می‌شود و منبع خالی می‌ماند. کپی یک بردار میلیونی میلی‌ثانیه‌ها هزینه دارد؛ Move فقط چند اشاره‌گر جابه‌جا می‌کند — تقریباً رایگان. std::move هم خودش چیزی را جابه‌جا نمی‌کند؛ فقط به کامپایلر قول می‌دهد که «این آبجکت را دیگر نمی‌خوانم، می‌توانی بدزدی‌اش»." },
      { k: "code", lang: "cpp", title: "move.cpp", code: "#include <vector>\n#include <utility>\n\nstd::vector<int> make_big() {\n    std::vector<int> v(1'000'000, 42);\n    return v;     // بدون Move: کپی میلیون‌ها int!\n}                 // با Move (یا NRVO): صفر کپی\n\nstd::vector<int> a = make_big();          // انتقال، نه کپی\nstd::vector<int> b = std::move(a);        // قول: a دیگر استفاده نمی‌شود\n// a حالا در وضعیت «معتبر ولی نامشخص» است — فقط جایگزینی (assignment) یا نابودی‌اش امن است\n\n// کلاسی که Move را بلد است:\nclass Buffer {\n    int* data_; size_t size_;\npublic:\n    Buffer(Buffer&& o) noexcept           // سازنده انتقال\n        : data_(o.data_), size_(o.size_) {\n        o.data_ = nullptr; o.size_ = 0;   // دزدیدن + خالی‌کردن منبع\n    }\n    Buffer& operator=(Buffer&& o) noexcept {\n        delete[] data_;\n        data_ = o.data_; size_ = o.size_;\n        o.data_ = nullptr; o.size_ = 0;\n        return *this;\n    }\n};" },
      { k: "p", t: "Rule of Five تکمیل‌کننده بحث RAII جلسه قبل است: اگر کلاسی یکی از این پنج را لازم داشت — سازنده کپی، عملگر کپی، سازنده انتقال، عملگر انتقال، ویراستار — معمولاً هر پنج را باید بنویسد (یا بهتر: = default و = delete بدهی تا کامپایلر و خواننده دقیقاً بدانند چه قراردادی داری). و بهترین کلاس‌ها اغلب Rule of Zero دارند: منابع را به اعضای هوشمند (unique_ptr، vector) بسپار تا خودت هیچ‌کدام را ننویسی. کپی ممنوعِ منحصربه‌فرد را هم بشناس: unique_ptr copy ندارد، فقط move — مالکیت دقیقاً یک نفر است و کامپایلر این قانون را اجرا می‌کند." },
      { k: "code", lang: "cpp", title: "templates.cpp", code: "// Template — یک الگوریتم برای همه تایپ‌ها، بدون هزینه اجرا:\ntemplate <typename T>\nT max_of(T a, T b) { return a > b ? a : b; }\n\nmax_of(3, 7);          // T = int   — در کامپایل ساخته می‌شود\nmax_of(2.5, 1.1);      // T = double\n\n// Template کلاس: Stack برای هر تایپی\ntemplate <typename T>\nclass Stack {\n    std::vector<T> items_;\npublic:\n    void push(T v)  { items_.push_back(std::move(v)); }\n    T pop() {\n        T top = std::move(items_.back());   // انتقال بیرون\n        items_.pop_back();\n        return top;\n    }\n};\nStack<std::string> names;   // فقط stringها — ایمنی تایپ کامل\nnames.push(\"سارا\");\n\n// مفاهیم مدرن (C++20): محدود کردن Template\n// template <typename T> requires std::integral<T>\n// T gcd(T a, T b) { ... }   ← فقط اعداد صحیح مجازند" },
      { k: "table", head: ["مفهوم", "چیست", "چرا مهم است"], rows: [["lvalue", "چیزی که نام و آدرس دارد", "قابل‌ارجاع و ماندگار"], ["rvalue", "موقت و رو به مرگ", "کاندیدای Move"], ["std::move", "تبدیل lvalue به rvalue (قول می‌دهم!)", "اجازه دزدی منابع"], ["noexcept", "قولِ بدون استثنا", "بدون آن، کانتینرها از Move صرف‌نظر می‌کنند!"]] },
      { k: "warn", title: "std::move اشتباه", t: "Move روی چیزی که بعدش دوباره خوانده می‌شود، باگ است — چون منبع خالی شده. مخصوصاً در حلقه‌ها: auto x = std::move(vec[i]) و بعد خواندن vec[i] فاجعه است. و noexcept را روی عملگرهای انتقال فراموش نکن؛ بدونش vector هنگام رشد، به‌جای انتقال، کپی می‌کند و عملاً همه سرعت از دست می‌رود." },
      { k: "tip", title: "نکته منتور", t: "Compiler Explorer (godbolt.org) را باز کن و تابعی که vector برمی‌گرداند را با و بدون -O2 ببین: NRVO چطور کپی را حذف می‌کند و Move چه اسمبلی‌ای تولید می‌کند. دیدن صفر بودن فراخوانی‌های کپی، Move Semantics را برای همیشه ملموس می‌کند." },
    ],
    quiz: [
      { q: "std::move واقعاً چه می‌کند؟", opts: ["داده را جابه‌جا می‌کند", "فقط یک تبدیل است که به کامپایلر اجازه دزدی منابع می‌دهد — انتقال را سازنده انتقال انجام می‌دهد", "حافظه آزاد می‌کند", "کپی عمیق می‌سازد"], ans: 1, why: "std::move فقط static_cast به rvalue reference است؛ کار واقعی را move constructor/assignment با جابه‌جا کردن اشاره‌گرها و خالی‌کردن منبع انجام می‌دهد." },
      { q: "چرا noexcept روی move constructor حیاتی است؟", opts: ["برای خوانایی است", "چون بدون آن، کانتینرها (مثل vector) هنگام رشد از ترس استثنا کپی می‌کنند نه انتقال", "کامپایلر اجبار می‌کند", "سرعت اسمبلی بیشتر"], ans: 1, why: "vector فقط وقتی می‌تواند با خیال راحت عناصر را منتقل کند که مطمئن باشد وسط کار استثنا پرت نمی‌شود؛ بدون noexcept به نسخه امن (کپی) برمی‌گردد." },
    ],
  },
  {
    id: "dp-x1",
    title: "ضدالگوها و Refactor به سمت الگوها",
    minutes: 50,
    blocks: [
      { k: "p", t: "الگوهای طراحی را نباید «از قبل» اعمال کرد — باید نشانه‌ها را شناخت و وقتی درد ظاهر شد، به‌سراغشان رفت. این درس درباره سه بوی بد رایج و الگویی است که درمانش می‌کند: زنجیره if/else که با هر نوع جدید بلندتر می‌شود (درمان: Strategy یا رجیستری)، کدی که برای انجام یک کار باید ده متد را پشت‌سرهم و به ترتیب صدا زد (درمان: Facade)، و کلاسی که همه‌چیز را می‌داند و همه از او می‌پرسند (درمان: تفکیک مسئولیت و Mediator). مهارت واقعی، «بوییدن» این حالت‌ها وسط کد معمولی است." },
      { k: "code", lang: "java", title: "refactor-strategy.java", code: "// ❌ بوی بد: با هر روش پرداخت جدید، این متد باز می‌شود\npublic double fee(Order o) {\n    if (o.method.equals(\"card\"))    return o.total * 0.02;\n    if (o.method.equals(\"wallet\"))  return 500;\n    if (o.method.equals(\"cod\"))     return o.total * 0.01 + 2000;\n    // ... و ماه بعد یک if دیگر ...\n}\n\n// ✓ Strategy: هر روش، یک پیاده‌سازی؛ متد اصلی دیگر هرگز باز نمی‌شود\ninterface FeePolicy { double fee(Order o); }\n\nrecord CardFee()   implements FeePolicy {\n    public double fee(Order o) { return o.total() * 0.02; }\n}\nrecord WalletFee() implements FeePolicy {\n    public double fee(Order o) { return 500; }\n}\n\nclass Checkout {\n    private final Map<String, FeePolicy> policies = Map.of(\n        \"card\", new CardFee(),\n        \"wallet\", new WalletFee());\n\n    double fee(Order o) {\n        var p = policies.get(o.method());\n        if (p == null) throw new IllegalArgumentException(o.method());\n        return p.fee(o);\n    }\n}" },
      { k: "code", lang: "py", title: "refactor-facade.py", code: "# ❌ مشتری باید این مراسم را بلد باشد:\nimg = load('photo.raw')\nnorm = normalize(img)\ndenoised = remove_noise(norm, strength=2)\nresized = resize(denoised, (1920, 1080))\nwatermarked = add_watermark(resized, 'bitcode')\nsave(watermarked, 'out.jpg')\n\n# ✓ Facade: یک در، پشتش همه مراسم\nclass PhotoPipeline:\n    def export(self, src, dst, size=(1920, 1080)):\n        img = self._load(src)\n        img = self._normalize(img)\n        img = self._denoise(img)\n        img = self._resize(img, size)\n        self._save(self._watermark(img), dst)\n\nPhotoPipeline().export('photo.raw', 'out.jpg')\n# جزئیات پشت در ماند؛ تغییر قدرت نویز‌گیری، هیچ مشتری‌ای را لمس نمی‌کند" },
      { k: "list", items: ["بوی God Class: فایل بالای ۵۰۰ خط که «همه‌چیزدان» است → تفکیک به Serviceهای کوچک + Mediator اگر هماهنگی لازم است", "بوی زنجیره وارثی عمیق: پنج سطح extends → ترکیب و Strategy", "بوی کپی‌پیست با ifهای متفاوت: سه کلاس ۹۰٪ مشابه → Template Method (اسکلت مشترک + قدم‌های قابل‌override)", "بوی فراخوانی‌های پراکنده ده‌تایی: عملیات واحدی که همه‌جا با همان ترتیب تکرار می‌شود → Facade"] },
      { k: "warn", title: "مهندسی بیش از حد", t: "الگو برای دردی است که وجود دارد، نه دردی که شاید بیاید. سه کلاس ساده با چند if خوانا، بهتر از معماری Strategy-Factory-Registry برای مسئله‌ای است که دو حالت دارد و احتمالاً همین دو حالت می‌ماند. قانون سه: وقتی برای سومین بار همان منطق را با تغییر جزئی کپی کردی، آنگاه انتزاع کن — قبلش زود است." },
      { k: "tip", title: "نکته منتور", t: "تمرین این هفته: یکی از پروژه‌هایت را باز کن و دنبال بلندترین زنجیره if/else بگرد. بدون تغییر رفتار، فقط همان یک جا را به دیکشنریِ Strategy تبدیل کن و تستش را بنویس. حس «کد دیگر از تغییر نمی‌ترسد» را که بچشی، بقیه الگوها خودشان سراغت می‌آیند." },
    ],
    quiz: [
      { q: "کی باید از Strategy استفاده کنیم؟", opts: ["همیشه برای هر شرطی", "وقتی چند رفتار هم‌خانواده داریم و احتمال افزودن/تعویض رفتار در اجرا هست", "فقط در جاوا", "وقتی کلاس بزرگ است"], ans: 1, why: "Strategy وقتی ارزشش را دارد که رفتارها قابل‌تعویض و افزایشی باشند — باز/بسته در عمل: افزودن رفتار جدید بدون دست‌زدن به کد موجود." },
      { q: "Facade چه چیزی را حل می‌کند؟", opts: ["پیچیدگی الگوریتم", "زیرسیستم پیچیده‌ای که مشتری‌ها مجبورند مراسمش را بدانند — یک در ساده جلویش می‌گذارد", "تعداد کلاس‌ها", "سرعت اجرا"], ans: 1, why: "Facade جزئیات را پشت یک API ساده پنهان می‌کند؛ مشتری فقط در را می‌بیند و تغییرات پشت در، آزادانه انجام می‌شود." },
    ],
  },
  {
    id: "test-x1",
    title: "تست یکپارچگی و API — لایه‌ای که هرم گم می‌کند",
    minutes: 55,
    blocks: [
      { k: "p", t: "تست واحد می‌گوید اجزا سالم‌اند؛ ولی باگ‌های واقعی عاشق «درزها» هستند: جایی که سرویس به دیتابیس می‌چسبد، جایی که JSON سریالایز می‌شود، جایی که کوئری واقعاً اجرا می‌شود. تست یکپارچگی همین درزها را با اجزای واقعی (یا نزدیک به واقعی) می‌سنجد — و برای API، یعنی فراخوانی واقعی endpoint با سرور بالا و دیتابیس واقعی و بررسی کد وضعیت، بدنه و عوارض جانبی. چون کندند (ثانیه در برابر میلی‌ثانیه)، تعدادشان کمتر است — ولی همان‌هایی‌اند که «روی ماشین من کار می‌کرد» را قبل از Production می‌گیرند." },
      { k: "code", lang: "py", title: "test_api_integration.py", code: "import pytest\nfrom httpx import AsyncClient\nfrom app.main import app\nfrom app.db import engine\n\n@pytest.fixture\nasync def client():\n    # دیتابیس تست جدا — قبل/بعد هر تست، تمیز\n    async with engine.begin() as c:\n        await c.execute(SCHEMA_SQL)\n    async with AsyncClient(app=app, base_url='http://t') as c:\n        yield c\n    async with engine.begin() as c:\n        await c.execute('TRUNCATE orders, customers RESTART IDENTITY')\n\n@pytest.mark.asyncio\nasync def test_create_order_full_cycle(client):\n    # ۱) عمل واقعی از درِ HTTP\n    r = await client.post('/api/orders', json={\n        'customer_id': 'cus-1', 'items': [{'sku': 'A', 'qty': 2}]})\n\n    # ۲) قرارداد HTTP\n    assert r.status_code == 201\n    body = r.json()\n    assert body['status'] == 'pending'\n    assert 'Location' in r.headers\n\n    # ۳) عارضه جانبی واقعی در دیتابیس\n    r2 = await client.get(body['id'])\n    assert r2.json()['total'] == 70000    # قیمت از کاتالوگ واقعی آمد" },
      { k: "table", head: ["", "تست واحد", "تست یکپارچگی", "End-to-End"], rows: [["مرزها", "یک تابع/کلاس", "یک سرویس با وابستگی‌های واقعی‌اش", "کل سیستم + UI"], ["سرعت", "میلی‌ثانیه", "صدم ثانیه تا ثانیه", "دقیقه"], ["دیتابیس", "Mock/خاطره‌ای", "واقعی (کانتینر تست)", "واقعیِ staging"], ["تعداد در هرم", "زیاد", "متوسط", "کم و گزیده"], ["چه می‌گیرد؟", "خطای منطق", "خطای اتصال و قرارداد", "خطای مسیر کامل کاربر"]] },
      { k: "p", t: "دو تصمیم زیرساختی، تست یکپارچگی را از دردناق به لذت‌بخش تبدیل می‌کنند: اول، دیتابیس واقعیِ یک‌بارمصرف — با Testcontainers (کانتینر Postgres که برای تست بالا می‌آید و بعد نابود می‌شود) یا SQLite-in-memory برای سبک‌ترها؛ Mock کردنِ لایه دیتابیس یعنی داری ORM خودت را تست می‌کنی، نه کوئری‌هایت را. دوم، ایزوله‌کردن تست‌ها: هیچ تستی به خروجی تست قبلی وابسته نباشد — هر تست داده خودش را بسازد و بعدش تمیز کند؛ وگرنه ترتیب اجرا تعیین‌کننده می‌شود و تست‌ها «گاهی» می‌شکنند." },
      { k: "code", lang: "py", title: "contract-boundaries.py", code: "# برای مرزهای بیرونی (API پرداختِ شریک تجاری):\n# Consumer-Driven Contract — ما تعریف می‌کنیم چه انتظاری داریم\n\nclass PaymentClient:                # کلاینت واقعی ما\n    def __init__(self, http): self.http = http\n    def charge(self, order):\n        r = self.http.post('/charge', json={'order': order.id,\n                                            'amount': order.total})\n        r.raise_for_status()\n        return r.json()['ref']\n\n# تست قرارداد: سرورِ فرضیِ Pact/ WireMock همین رفتار را تقلید می‌کند؛\n# و در CIِ طرف مقابل، همان قرارداد اجرا می‌شود تا اگر روزی\n# APIشان تغییر کرد، قبل از Production بفهمیم — نه بعدش.\n\n# تست مرزهای زمانی هم فراموش نشود:\ndef test_timeout_falls_back(monkeypatch):\n    monkeypatch.setenv('PAY_TIMEOUT', '0.01')\n    with pytest.raises(TimeoutError):\n        client.charge(order)        # بعدش: مسیر جایگزین فعال می‌شود؟" },
      { k: "tip", title: "نکته منتور", t: "قانون ۸۰/۲۰ تست API: پنج مسیر را عمیق تست کن (شاد، ورودی بد، غیرمجاز، تعارض، خطای وابستگی) و بقیه endpointها را با یک پیمایش سطحی. تیم‌هایی که ۵۰۰ تست API شکننده دارند، از تیم‌هایی که ۵۰ تستِ مرزها را محکم گرفته‌اند، عقب‌ترند — نه جلوتر." },
    ],
    quiz: [
      { q: "چرا Mock کردن کامل دیتابیس در تست یکپارچگی اشتباه است؟", opts: ["چون کند است", "چون آن‌وقت ORM و کد خودت را تست می‌کنی، نه کوئری واقعی و قرارداد دیتابیس را — دقیقاً همان درزی که باید سنجیده شود", "چون امنیت ندارد", "چون ممکن نیست"], ans: 1, why: "باگ‌های SQL (نام ستون، نوع، قفل) فقط با دیتابیس واقعی ظاهر می‌شوند؛ Mock همیشه «چیزی که فکر می‌کنی دیتابیس می‌گوید» را می‌گوید." },
      { q: "Contract Testing چه دردی را دوا می‌کند؟", opts: ["کندی تست‌ها", "تغییر ناگهانی API سرویس‌های وابسته که تا Production لو نمی‌رود", "تعداد تست‌ها", "نیاز به CI"], ans: 1, why: "قرارداد مشترک در CI هر دو طرف اجرا می‌شود؛ تغییر شکست‌ساز طرف مقابل، قبل از ریلیز قرمز می‌شود — نه پنجشنبه شب در Production." },
    ],
  },
  {
    id: "react-x2",
    title: "کارایی React — memo، Profiler و جنگ رندرهای بیهوده",
    minutes: 55,
    blocks: [
      { k: "p", t: "رندر شدن در React ارزان است — Virtual DOM فقط محاسبه می‌کند؛ ولی وقتی کامپوننتی هزاران بار بیهوده رندر شود، جمعش سنگین می‌شود. قبل از هر بهینه‌سازی، قانون اول: اندازه بگیر. React DevTools Profiler را باز کن، یک عمل کاربر را ضبط کن و ببین چه کسی چند بار رندر شد — ۹۰٪ «مشکلات کارایی» اصلاً وجود ندارند و ۱۰٪ واقعی هم معمولاً یک رندر سنگین در جای مشخص‌اند، نه هزار رندر پخش. memo و useMemo را قبل از اندازه‌گیری نزن؛ هر کدام هزینه مقایسه خودشان را دارند و برای کامپوننت‌های سبک، خالص ضررند." },
      { k: "code", lang: "tsx", title: "render-storm.tsx", code: "// ❌ طوفان رندر: هر تایپ در جست‌وجو، کل لیست ۵۰۰ ردیفی رندر می‌شود\nfunction Page() {\n  const [query, setQuery] = useState('');\n  const rows = data.filter(...);          // هر رندر، دوباره محاسبه\n  return (\n    <>\n      <input value={query} onChange={(e) => setQuery(e.target.value)} />\n      <BigTable rows={rows} />            {/* ۵۰۰ رندر به‌ازای هر حرف! */}\n    </>\n  );\n}\n\n// ✓ درمان اول: محاسبه فقط وقتی ورودی‌اش عوض شد\nconst rows = useMemo(() => data.filter(...), [data]);\n\n// ✓ درمان دوم: کامپوننت فقط وقتی props عوض شد رندر شود\nconst BigTable = memo(function BigTable({ rows }) {\n  return <table>{rows.map(...)}</table>;\n});\n\n// ⚠ ولی memo با callback جدید هر رندر باطل می‌شود:\n<Row onSelect={() => select(id)} />      {/* هر رندر تابع تازه! */}\nconst onSelect = useCallback(select, []); // ← حالا مرجع ثابت است\n<Row onSelect={onSelect} />" },
      { k: "p", t: "ولی قوی‌ترین بهینه‌سازی React اصلاً memo نیست — «ساختار» است: State را تا جایی که می‌شود پایین ببر (State جست‌وجو مالِ کامپوننت جست‌وجوست، نه کل صفحه)؛ بخش‌های پرتغییر را از بخش‌های گران ایزوله کن (Composition: children از بیرون می‌آیند و با رندر داخلی دوباره ساخته نمی‌شوند)؛ و لیست‌های بزرگ را Virtualize کن (فقط ردیف‌های دیده‌شده در DOM باشند — react-window). این سه تغییر ساختاری، معمولاً ده برابر همه memoهای دنیا اثر دارند و کد را هم ساده‌تر می‌کنند نه پیچیده‌تر." },
      { k: "code", lang: "tsx", title: "composition-wins.tsx", code: "// ❌ هر تیکِ ساعت، گراف سنگین هم رندر می‌شود\nfunction Dashboard() {\n  const [now, setNow] = useState(Date.now());\n  useEffect(() => { const t = setInterval(() => setNow(Date.now()), 1000);\n                    return () => clearInterval(t); }, []);\n  return (\n    <>\n      <Clock now={now} />        {/* سبک — باید هر ثانیه رندر شود */}\n      <HeavyChart data={data} /> {/* سنگین — چرا باید رندر شود؟ */}\n    </>\n  );\n}\n\n// ✓ جداسازی: رندرِ ثانیه‌ای فقط Clock را لمس می‌کند\nfunction Dashboard() {\n  return (\n    <>\n      <Ticker>                   {/* State داغ این‌جاست */}\n        <Clock />\n      </Ticker>\n      <HeavyChart data={data} /> {/* دیگر هرگز بی‌دلیل رندر نمی‌شود */}\n    </>\n  );\n}" },
      { k: "table", head: ["ابزار", "مسئله‌اش", "کی بزنیم"], rows: [["ساختار (State پایین/ایزوله)", "رندر بیهوده از اساس", "همیشه — اول از همه"], ["Virtualization", "لیست‌های بلند", "هر لیست بالای ~۱۰۰ ردیف"], ["memo", "کامپوننت گران با props پایدار", "بعد از اثبات مشکل در Profiler"], ["useMemo/useCallback", "ورودی‌های memo یا محاسبات گران", "فقط جایی که اندازه‌گیری نشان داده"], ["Transition (useTransition)", "UI حین کار سنگین قفل می‌شود", "جست‌وجو/فیلتر همزمان با رندر بزرگ"]] },
      { k: "warn", title: "بت‌سازی memo", t: "پروژه‌هایی که هر کامپوننتشان memo و هر تابعشان useCallback دارد، معمولاً هم کندترند (هزاران مقایسه بیهوده در هر رندر) و هم خوانایی‌شان قربانی شده. memo پیش‌فرض نیست — نسخه است. و اگر memo گذاشتی ولی اثر نکرد، اول وابستگی‌هایش را چک کن: آبجکت یا تابع تازه‌ساز در props، هر رندر مرجع را عوض می‌کند و memo را باطل." },
      { k: "tip", title: "نکته منتور", t: "یک بازی آموزشی عالی: Profiler را باز کن و «highlight updates» را روشن کن — بعد در اپت کلیک کن و ببین چه چیزهایی چشمک می‌زنند. جایی که چشمک نباید باشد، درس امروز شروع می‌شود. این دیدنِ رندر، مهارتی است که مصاحبه‌های «چرا اپ کند است» را یک‌جا حل می‌کند." },
    ],
    quiz: [
      { q: "چرا memo روی کامپوننتی که callback تازه‌ساز می‌گیرد بی‌اثر است؟", opts: ["چون memo خراب است", "چون مرجع تابع در هر رندر عوض می‌شود و مقایسه props همیشه «تغییر کرد» می‌گوید — باید useCallback", "چون کامپوننت Stateless است", "چون React نسخه قدیمی است"], ans: 1, why: "memo با Object.is مقایسه می‌کند؛ () => {} هر بار تابع جدیدی است. useCallback مرجع را تا وقتی وابستگی‌ها ثابت‌اند، حفظ می‌کند." },
      { q: "اولین قدم واقعی برای کارایی React چیست؟", opts: ["memo گذاشتن همه‌جا", "اندازه‌گیری با Profiler برای یافتن رندرهای واقعاً بیهوده یا سنگین", "تغییر کتابخانه", "کوچک‌کردن کامپوننت‌ها"], ans: 1, why: "بدون داده، بهینه‌سازی حدس است — و حدس در React معمولاً memoهای بیهوده تولید می‌کند. Profiler گلوگاه واقعی را در ۳۰ ثانیه نشان می‌دهد." },
    ],
  },
  {
    id: "node-x2",
    title: "احراز هویت در Node — از Session تا JWT عملی",
    minutes: 55,
    blocks: [
      { k: "p", t: "هر API بالاخره به این سوال می‌رسد: «این درخواست از طرف کیست و اجازه‌اش چیست؟» در این درس یک سیستم ورود واقعی می‌سازیم با همه اجزایش: هش رمز با bcrypt (هرگز ذخیره متن‌ساده!)، Session یا JWT، Middleware محافظ مسیر، و نقش‌ها. مهم‌تر از کد، تصمیم‌هاست: Session برای اپ‌های تک‌سرور با نیاز به ابطال فوری؛ JWT برای معماری سرویسی و Stateless — و در هر دو، کوکی HttpOnly خانه امن توکن است، نه LocalStorage." },
      { k: "code", lang: "js", title: "auth.js", code: "const bcrypt = require('bcrypt');\nconst jwt = require('jsonwebtoken');\n\n// ثبت‌نام — هش کند و نمک‌دار؛ reverse مهندسی‌ناپذیر\nrouter.post('/register', async (req, res) => {\n  const { email, password } = req.body;\n  if (!isEmail(email) || password.length < 8)\n    return res.status(422).json({ error: 'ورودی نامعتبر' });\n\n  const hash = await bcrypt.hash(password, 12);  // cost 12 ≈ ۲۵۰ms عمدی!\n  await db.users.insert({ email, hash });        // hash ذخیره می‌شود نه رمز\n  res.status(201).end();\n});\n\n// ورود — مقایسه امن و صدور توکن\nrouter.post('/login', async (req, res) => {\n  const user = await db.users.byEmail(req.body.email);\n  const ok = user && await bcrypt.compare(req.body.password, user.hash);\n  if (!ok) return res.status(401).json({ error: 'invalid' });\n  // ↑ همان پیام برای «کاربر نیست» و «رمز اشتباه» — اطلاعات نده!\n\n  const token = jwt.sign({ sub: user.id, role: user.role },\n                         process.env.JWT_SECRET, { expiresIn: '15m' });\n  res.json({ access: token });\n});\n\n// Middleware محافظ — همه مسیرهای /api/me پشت این درند\nfunction auth(req, res, next) {\n  const token = req.headers.authorization?.replace('Bearer ', '');\n  try {\n    req.user = jwt.verify(token, process.env.JWT_SECRET);\n    next();\n  } catch {\n    res.status(401).json({ error: 'unauthorized' });\n  }\n}\n\nconst adminOnly = (req, res, next) =>\n  req.user.role === 'admin' ? next() : res.status(403).end();\n\nrouter.get('/api/me', auth, (req, res) => res.json({ id: req.user.sub }));\nrouter.delete('/api/users/:id', auth, adminOnly, removeUser);" },
      { k: "list", items: ["bcrypt/scrypt/argon2 — هش کند و نمک‌دار؛ MD5 و SHA سریع‌اند و برای رمز عبور یعنی دعوت از حمله", "Secret از متغیر محیطی — نه کد، نه ریپازیتوری، نه لاگ؛ و برای هر محیط جدا", "پیام‌های خطای یکسان برای کاربرِ ناموجود و رمز اشتباه — جلوگیری از شمارش کاربران معتبر", "نرخ‌محدودکننده روی /login (مثل ۵ تلاش در ۱۵ دقیقه) — کندترین حمله Brute-force با این یک خط می‌میرد", "Refresh Token با چرخش و HttpOnly — Access کوتاه‌عمر (۱۵ دقیقه) پنجره دزدی را کوچک می‌کند"] },
      { k: "code", lang: "js", title: "rate-limit.js", code: "// محافظ ورود در برابر brute force — پنج خط که شب را نجات می‌دهد:\nconst attempts = new Map();   // در تولید: Redis\n\nfunction loginLimiter(req, res, next) {\n  const key = req.ip + ':' + req.body.email;\n  const now = Date.now();\n  const tries = (attempts.get(key) ?? []).filter(t => now - t < 15 * 60_000);\n  if (tries.length >= 5) return res.status(429)\n    .json({ error: 'زیاد تلاش کردی؛ ۱۵ دقیقه صبر کن' });\n  tries.push(now);\n  attempts.set(key, tries);\n  next();\n}\n\napp.post('/login', loginLimiter, loginHandler);" },
      { k: "warn", title: "سه اشتباه که لاگ‌ها را پر می‌کند", t: "۱) توکن JWT بدون exp — توکنی که منقضی نمی‌شود، کلید مادام‌العمر است. ۲) verify را با try/catch نگرفتن — اولین توکن منقضی، سرور را ۵۰۰ می‌کند. ۳) چاپ req.body در لاگ «برای دیباگ» — یعنی رمز عبور همه کاربران، متن ساده، در لاگ مرکزی. لاگر را طوری تنظیم کن فیلدهای حساس را ماسک کند؛ یک grep روی لاگ‌هایت بزن و ببین چه می‌یابی." },
      { k: "tip", title: "نکته منتور", t: "قبل از اختراع دوباره چرخ، passport.js و Auth.js را ببین — ولی یک‌بار این نسخه دستی را بنویس؛ چون روزی که نشستِ کاربر «به‌شکل عجیبی» خراب شد، فقط کسی که لایه‌ها را می‌فهمد می‌تواند بفهمد کجای زنجیره (هش؟ توکن؟ کوکی؟ زمان سرور؟) شکسته است." },
    ],
    quiz: [
      { q: "چرا bcrypt به‌عمد «کند» است؟", opts: ["مشکل پیاده‌سازی است", "تا brute force و Rainbow Table گران شود — هر حدس ۲۵۰ میلی‌ثانیه یعنی میلیون‌ها سال برای یک دیتابیس لو رفته", "برای امنیت شبکه", "برای کش بهتر"], ans: 1, why: "کاربر واقعی یک‌بار لاگین می‌کند و ۲۵۰ms را حس نمی‌کند؛ ولی مهاجم باید میلیاردها حدس بزند — هرکدام ۲۵۰ms. کندبودن اینجا ویژگی است." },
      { q: "Access Token کوتاه‌عمر + Refresh چرخان چه چیزی را محدود می‌کند؟", opts: ["تعداد کاربران", "پنجره زمانی سوءاستفاده از توکن لو رفته و امکان کشف استفاده غیرمجاز", "سرعت سرور", "حجم دیتابیس"], ans: 1, why: "اگر Access بدزدیده شود، ۱۵ دقیقه بعد مرده است؛ و اگر دزد بخواهد با Refresh قدیمی (بعد از چرخش) وارد شود، سیستم دزدی را می‌فهمد و همه نشست‌ها را می‌سوزاند." },
    ],
  },
];
